version: '2'

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 8042:80
    links:
      - mersea:app-container
    volumes_from:
      - mersea:ro
    restart: always

  mersea:
    image: mersea/mersea:latest
    command: /bin/sh -c "export SECRET_KEY_BASE=$$(bundle exec rake secret) && bundle exec rake db:create db:migrate && bundle exec puma -p 3000"
    ports:
      - 127.0.0.1:3000:3000
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MERSEA_DATABASE_USERNAME: postgres
      MERSEA_DATABASE_PASSWORD: postgres
      MERSEA_DATABASE_HOST: postgres
      MERSEA_DATABASE_PORT: 5432
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      BUGSNAG_API_KEY: ${BUGSNAG_API_KEY}
    restart: always

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 127.0.0.1:5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/db:/var/lib/postgresql/data/pgdata
    restart: always
