version: 2
jobs:
  rails_test:
    working_directory: ~/mersea-ruby
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root

      # Service container image available at `host: localhost`

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - mersea-{{ checksum "Gemfile.lock" }}
            - mersea-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install postgresql-client

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run:
          name: Parallel RSpec
          command: bundle exec rspec

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  tests:
    jobs:
      - rails_test
