default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['MERSEA_DATABASE_HOST'] || 'localhost' %>
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: mersea_development

test:
  <<: *default
  database: mersea_test

production:
  <<: *default
  database: mersea_production
  pool: <%= ENV['MERSEA_DATABASE_POOL'] || 20 %>
  host: <%= ENV['MERSEA_DATABASE_HOST'] %>
  port: <%= ENV['MERSEA_DATABASE_PORT'] %>
  username: <%= ENV['MERSEA_DATABASE_USERNAME'] %>
  password: <%= ENV['MERSEA_DATABASE_PASSWORD'] %>
