defaults: &defaults
  recaptcha:
    site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
    secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  postmark: &postmark
    api_key: <%= ENV['POSTMARK_API_KEY'] %>
    from: <%= ENV['POSTMARK_FROM'] %>
    template_ids:
      reset_password: <%= ENV['POSTMARK_TEMPLATE_RESET_PASSWORD_ID'] %>
  bugsnag:
    api_key: <%= ENV['BUGSNAG_API_KEY'] %>
  host: <%= ENV['MERSEA_HOST'] || 'localhost:3000' %>

development:
  <<: *defaults
  secret_key_base: 09891fd12ecf19f620830f731e57c33bdb5cbbd5e0bb7063eb13b0626e3a95c80094ef56543874aadc7e4512bb718ef5dae500eccbb92e7bc3985a0ef11481a3

test:
  <<: *defaults
  secret_key_base: 560e446b57b28d1681b3347c27d2da6d6f26c78403d73c6e70269a7519d591f37630944bce5ac8372a9d75bf7c706fa68a38a2ce6f1d812204676b4f2968843b

production:
  <<: *defaults
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
