on:
- push
- pull_request
name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install MRI
      uses: ruby/setup-ruby@v1
      with:
        # ruby-version: 2.7 # Not needed with a .ruby-version file
        bundler-cache: true
    - name: Database create
      run: bundle exec rake db:create
    - name: Database migration
      run: bundle exec rake db:schema:load
    - name: Test
      run: bundle exec rspec
